### ISSUE TITLE
Scroll textarea to bottom

### ISSUE THREAD

**Issue by riceguitar** [riceguitar/notedeck#3]
Copying something to notes should force the textarea to scroll to bottom.

fix is: 
$('#textarea_id').scrollTop($('#textarea_id')[0].scrollHeight);
http://stackoverflow.com/questions/7373081/how-to-have-a-textarea-to-keep-scrolled-to-the-bottom-when-updated

**Comment by terrancewoest** [comment]
Just used that to fix it.
