### ISSUE TITLE
Blank page on home page for decks

### ISSUE THREAD

**Issue by terrancewoest** [riceguitar/notedeck#4]
When you go to the decks page rather than a specific page it is just blank. Maybe we could add some functionality where the user can choose a page template from the theme.

**Comment by riceguitar** [comment]
Goodcall, we should probably have the "archive" fall back to the default theme so that we don't have to style it for now. Let's look into falling back when possible.

**Comment by terrancewoest** [comment]
The Deck post type's "archive" page, now just returns the standard theme template.
